blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (
    ArticleCreateView,
    ArticleDeleteView,
    ArticleDetailView,
    ArticleUpdateView,
    main_page
)
from .apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("", cache_page(10)(main_page), name="main_page"),
    path("create/", ArticleCreateView.as_view(), name="create_article"),
    path("detail/<int:pk>/", ArticleDetailView.as_view(), name="detail_article"),
    path("update/<int:pk>/", ArticleUpdateView.as_view(), name="update_article"),
    path("delete/<int:pk>", ArticleDeleteView.as_view(), name="delete_article"),
]

clients/urls.py
from config.urls import path
from clients.apps import ClientsConfig
from .views import (
    ClientsListView,
    ClientsDetailView,
    ClientsCreateView,
    ClientsDeleteView,
    ClientsUpdateView,
)


app_name = ClientsConfig.name

urlpatterns = [
    path("", ClientsListView.as_view(), name="clients"),
    path("create_client/", ClientsCreateView.as_view(), name="create_client"),
    path("delete_client/<int:pk>", ClientsDeleteView.as_view(), name="delete_client"),
    path("edit_client/<int:pk>", ClientsUpdateView.as_view(), name="edit_client"),
    path("detail_client/<int:pk>", ClientsDetailView.as_view(), name="detail_client"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("", include("newsletter.urls", namespace="newsletter")),
    path("clients/", include("clients.urls", namespace="clients")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import NewsletterConfig
from .views import (
    NewsLetterListView,
    NewsLetterCreateView,
    NewsLetterDeleteView,
    NewsLetterDetailView,
    NewsLetterUpdateView,
    MessageCreateView,
    MessageUpdateView,
    MessageDetailView,
    MessageDeleteView,
    main_page,
    recipients_list,
    distribution_attempts,
)

app_name = NewsletterConfig.name

urlpatterns = [
    path("", main_page, name="main_page"),
    # CRUD urls for newsletter.
    path(
        "create_newsletter/", NewsLetterCreateView.as_view(), name="create_newsletter"
    ),
    path(
        "detail_newsletter/<int:pk>",
        NewsLetterDetailView.as_view(),
        name="detail_newsletter",
    ),
    path(
        "newsletters/", cache_page(60)(NewsLetterListView.as_view()), name="newsletters"
    ),
    path(
        "edit_newsletter/<int:pk>",
        NewsLetterUpdateView.as_view(),
        name="edit_newsletter",
    ),
    path(
        "delete_newsletter/<int:pk>",
        NewsLetterDeleteView.as_view(),
        name="delete_newsletter",
    ),
    # CRUD urls for messages.
    path("create_message/", MessageCreateView.as_view(), name="create_message"),
    path("detail_message/<int:pk>", MessageDetailView.as_view(), name="detail_message"),
    path("edit_message/<int:pk>", MessageUpdateView.as_view(), name="edit_message"),
    path("delete_message/<int:pk>", MessageDeleteView.as_view(), name="delete_message"),
    # url for getting recipients list.
    path("recipients/<int:pk>", recipients_list, name="recipients"),
    # url for
    path("newsletters/<int:pk>/attempts/", distribution_attempts, name="attempts"),
]

newsletter/models.py
from django.db import models
from django.urls import reverse

from clients.models import Client
from users.models import User


# Create your models here.


class Message(models.Model):

    title = models.CharField(max_length=50, verbose_name="тема сообщения")
    body = models.TextField(verbose_name="текст сообщения")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="владелец")

    class Meta:
        verbose_name = "сообщение"
        verbose_name_plural = "сообщения"

    def __str__(self):
        return f"{self.title}"


class NewsLetter(models.Model):

    class Regularity(models.TextChoices):
        DAILY = "ежедневно"
        WEEKLY = "еженедельно"
        MONTHLY = "ежемесячно"

    class Status(models.TextChoices):
        COMPLETED = "завершена"
        CREATED = "создана"
        RUNNING = "запущена"

    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="автор")
    start_date = models.DateTimeField(verbose_name="дата первой отправки")
    end_date = models.DateTimeField(verbose_name="дата завершения")
    message = models.OneToOneField(
        Message,
        on_delete=models.CASCADE,
        related_name="newsletter",
        verbose_name="сообщение",
    )
    recipient = models.ManyToManyField(
        Client, related_name="recipients", verbose_name="получатель"
    )
    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.CREATED,
        verbose_name="статус",
    )
    regularity = models.CharField(
        max_length=15, choices=Regularity.choices, verbose_name="периодичность"
    )

    class Meta:
        verbose_name = "рассылка"
        verbose_name_plural = "рассылки"
        ordering = ["status", "start_date"]
        permissions = [("change_newsletter_status", "Can change newsletter status")]

    def __str__(self):
        return f"Рассылка: {self.pk}, Статус: {self.status}, Периодичность: {self.regularity}"

    def get_absolute_url(self):
        return reverse("newsletter:detail_newsletter", args=[self.pk])


class DistributionAttempt(models.Model):

    class Status(models.TextChoices):

        SUCCESSFUL = "Успешно"
        UNSUCCESSFUL = "Не успешно"

    last_try = models.DateTimeField(auto_now_add=True, verbose_name="дата отправки")
    status = models.CharField(
        max_length=10, choices=Status.choices, verbose_name="статус"
    )
    server_response = models.TextField(verbose_name="ответ сервера")
    newsletter = models.ForeignKey(
        NewsLetter,
        verbose_name="рассылка",
        on_delete=models.CASCADE,
        related_name="attempts",
    )

    class Meta:

        verbose_name = "попытка рассылки"
        verbose_name_plural = "попытки рассылки"
        ordering = ["-last_try"]

    def __str__(self):
        return f"{self.last_try}-{self.status}"

newsletter/forms.py
from django import forms
from django.forms import DateTimeInput
from django.utils import timezone

from clients.models import Client
from .models import NewsLetter, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class NewsLetterCreateForm(StyleFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):

        self.request = kwargs.pop("request")
        super(NewsLetterCreateForm, self).__init__(*args, **kwargs)
        self.fields["recipient"].queryset = Client.objects.filter(
            owner=self.request.user
        )
        self.fields["message"].queryset = Message.objects.filter(
            owner=self.request.user
        )

    class Meta:
        model = NewsLetter
        fields = "__all__"
        exclude = [
            "owner",
        ]
        widgets = {
            "start_date": DateTimeInput(
                format="%Y-%m-%d %H:%M", attrs={"type": "datetime-local"}
            ),
            "end_date": DateTimeInput(
                format="%Y-%m-%d %H:%M", attrs={"type": "datetime-local"}
            ),
        }

    def clean_start_date(self):
        cd = self.cleaned_data
        if cd["start_date"] < timezone.now():
            raise forms.ValidationError("Нельзя указать прошедшее время.")
        return cd["start_date"]

    def clean_end_date(self):
        cd = self.cleaned_data
        if cd["end_date"] < timezone.now():
            raise forms.ValidationError("Нельзя указать прошедшее время.")
        return cd["end_date"]


class NewsLetterUpdateForm(StyleFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):

        self.request = kwargs.pop("request")
        super(NewsLetterUpdateForm, self).__init__(*args, **kwargs)
        self.fields["recipient"].queryset = Client.objects.filter(
            owner=self.request.user
        )
        self.fields["message"].queryset = Message.objects.filter(
            owner=self.request.user
        )

    class Meta:
        model = NewsLetter
        fields = "__all__"
        exclude = [
            "owner",
        ]
        widgets = {
            "start_date": DateTimeInput(
                format="%Y-%m-%d %H:%M", attrs={"type": "datetime-local"}
            ),
            "end_date": DateTimeInput(
                format="%Y-%m-%d %H:%M", attrs={"type": "datetime-local"}
            ),
        }

    def clean_start_date(self):
        cd = self.cleaned_data
        if cd["start_date"] < timezone.now():
            raise forms.ValidationError("Нельзя указать прошедшее время.")
        return cd["start_date"]

    def clean_end_date(self):
        cd = self.cleaned_data
        if cd["end_date"] < timezone.now():
            raise forms.ValidationError("Нельзя указать прошедшее время.")
        return cd["end_date"]


class MessageCreateForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Message
        fields = "__all__"
        exclude = [
            "owner",
        ]


class MessageUpdateForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Message
        fields = "__all__"
        exclude = [
            "owner",
        ]


class ContentManagerUpdateNewsLetterForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = NewsLetter
        fields = [
            "status",
        ]

newsletter/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic import (
    CreateView,
    UpdateView,
    ListView,
    DetailView,
    DeleteView,
)

from .custom_mixins import (
    NewsLetterOwnerMixin,
    NewsLetterOwnerCreateMixin,
    NewsLetterOwnerUpdateMixin,
    MessageOwnerCreateMixin,
    MessageOwnerUpdateMixin,
    MessageOwnerMixin,
)
from .forms import (
    NewsLetterCreateForm,
    NewsLetterUpdateForm,
    MessageCreateForm,
    MessageUpdateForm,
    ContentManagerUpdateNewsLetterForm,
)
from .models import NewsLetter, Message


# Create your views here.
@login_required
def recipients_list(request, pk):
    recipients = NewsLetter.objects.get(pk=pk).recipient.all()
    return render(
        request, "newsletter/recipients_list.html", {"recipients": recipients}
    )


@login_required
def main_page(request):
    return render(request, "newsletter/main_page.html")


class NewsLetterListView(NewsLetterOwnerMixin, ListView):
    context_object_name = "newsletters"
    permission_required = "newsletter.Can_view_newsletters"


class NewsLetterCreateView(NewsLetterOwnerCreateMixin, CreateView):

    context_object_name = "newsletter"
    form_class = NewsLetterCreateForm
    permission_required = "newsletter.Can_create_newsletter"

    def get_form_kwargs(self):

        kwargs = super(NewsLetterCreateView, self).get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs


class NewsLetterDetailView(DetailView):
    model = NewsLetter
    context_object_name = "newsletter"
    permission_required = "newsletter.Can_edit_newsletter"


class NewsLetterUpdateView(NewsLetterOwnerUpdateMixin, UpdateView):
    context_object_name = "newsletter"
    form_class = NewsLetterUpdateForm
    permission_required = "newsletter.Can_edit_newsletter"

    def get_form_class(self):
        if self.request.user.is_staff:
            return ContentManagerUpdateNewsLetterForm
        return NewsLetterUpdateForm

    def get_form_kwargs(self):

        kwargs = super(NewsLetterUpdateView, self).get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs


class NewsLetterDeleteView(NewsLetterOwnerMixin, DeleteView):

    context_object_name = "newsletter"
    permission_required = "newsletter.Can_delete_newsletter"


class MessageListView(MessageOwnerMixin, ListView):
    context_object_name = "messages"
    permission_required = "newsletter.Can_view_message"


class MessageCreateView(MessageOwnerCreateMixin, CreateView):
    form_class = MessageCreateForm
    context_object_name = "message"
    permission_required = "newsletter.Can_create_message"


class MessageDetailView(DetailView):
    model = Message
    context_object_name = "message"
    permission_required = "newsletter.Can_edit_message"


class MessageUpdateView(MessageOwnerUpdateMixin, UpdateView):
    context_object_name = "message"
    form_class = MessageUpdateForm
    permission_required = "newsletter.Can_edit_message"


class MessageDeleteView(MessageOwnerMixin, DeleteView):
    context_object_name = "message"
    permission_required = "newsletter.Can_delete_message"


@login_required
def distribution_attempts(request, pk):
    attempts = NewsLetter.objects.get(pk=pk).attempts.all()
    return render(
        request, "newsletter/distributionattempt_list.html", {"attempts": attempts}
    )

newsletter/templates/newsletter/distributionattempt_list.html
{% extends "clients/base.html" %}

{% block title %} История рассылок {% endblock %}
{% block options %}
<a class="p-2 btn btn-outline-primary" href="{% url 'newsletter:newsletters' %}"
   role="button">Список рассылок</a>
{% endblock %}
{% block content %}

<div class="container text-center">
    <div class="row">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Рассылка</th>
                <th scope="col">Статус</th>
                <th scope="col">Ответ сервера</th>
                <th scope="col">Последняя попытка</th>
            </tr>
            </thead>
            <tbody class="table-group-divider">
            {% for attempt in attempts %}
            <tr>
                <th scope="row">{{ attempt.newsletter.pk }}</th>
                <td>{{ attempt.status }}</td>
                <td>{{ attempt.server_response }}</td>
                <td>{{ attempt.last_try }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}

newsletter/templates/newsletter/main_page.html
{% extends "clients/base.html" %}

{% block title %} Главная страница {% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col-md-6">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Блог</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Блог</li>
                </ul>
                <div class="card-footer">
                    <a type="button" class="w-20 btn btn-lg btn-primary" href="{% url 'blog:main_page' %}" role="button">Перейти</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Сервис отправки рассылок</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Отправка рассылок по указаным адресам</li>
                </ul>
                <div class="card-footer">
                    <a type="button" class="w-20 btn btn-lg btn-primary" href="{% url 'newsletter:newsletters' %}" role="button">Перейти</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/message_confirm_delete.html
{% extends "clients/base.html" %}

{% block content %}
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">Удаление сообщения</h5>
        <p class="card-text">При удалении сообщения рассылка также исчезнет из списка
            </p>
        <form method="post">
            {% csrf_token %}
            <p>Хотите удалить {{ message.title }} из  каталога?</p>
            <button type="submit" class="btn btn-danger">Подтвердить</button>
            <a href="{% url 'clients:clients' %}" class="btn btn-warning">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/message_create_form.html
{% extends "clients/base.html" %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Создать сообщение</h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Создать</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</form>
{% endblock %}

newsletter/templates/newsletter/message_detail.html
{% extends "clients/base.html" %}

{% block title %} Просмотр сообщения {% endblock %}

{% block content %}
            <div class="card text-center mb-4 box-shadow w-50">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal"></h4>
                </div>
                <div class="card-subtitle">
                    <h6 class="card-subtitle mt-2 text-body-secondary">{{ message.title }}</h6>
                </div>
                <div class="card-body">
                    <h6>{{ message.body }}</h6>
                </div>
                <div class="card-footer">
                    <a class="btn btn-primary" href="{% url 'newsletter:edit_message' message.pk %}"
                       role="button">Изменить</a>
                    <a class="btn btn-danger" href="{% url 'newsletter:delete_message' message.pk %}"
                       role="button">Удалить</a>
                </div>
            </div>
{% endblock %}

newsletter/templates/newsletter/message_update_form.html
{% extends "clients/base.html" %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Изменить сообщение</h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Изменить</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</form>
{% endblock %}

newsletter/templates/newsletter/newsletter_confirm_delete.html
{% extends "clients/base.html" %}

{% block content %}
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">Удаление рассылки</h5>
        <p class="card-text">При удалении рассылка исчезнет из списка
            </p>
        <form method="post">
            {% csrf_token %}
            <p>Хотите удалить рассылку {{ newsletter.pk }} из списка?</p>
            <button type="submit" class="btn btn-danger">Подтвердить</button>
            <a href="{% url 'clients:clients' %}" class="btn btn-warning">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/newsletter_create_form.html
{% extends "clients/base.html" %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Создать рассылку</h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Создать</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</form>
{% endblock %}

newsletter/templates/newsletter/newsletter_detail.html
{% extends "clients/base.html" %}

{% block title %} Просмотр рассылки {% endblock %}

{% block content %}
            <div class="card text-center mb-4 box-shadow w-50">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Рассылка - {{ newsletter.pk }}</h4>
                </div>
                <div class="card-subtitle">
                    <h6 class="card-subtitle mt-2 text-body-secondary">Дата начала {{ newsletter.start_date }}</h6>
                </div>
                <div class="card-body">
                    <h6>Получатели: {% for recipient in newsletter.recipient.all %} {{recipient.get_full_name}}, {% endfor %}</h6>
                </div>
                <div class="card-footer">
                    <a class="btn btn-primary" href="{% url 'newsletter:edit_newsletter' newsletter.pk %}"
                       role="button">Изменить</a>
                    <a class="btn btn-danger" href="{% url 'newsletter:delete_newsletter' newsletter.pk %}"
                       role="button">Удалить</a>
                </div>
            </div>
{% endblock %}

newsletter/templates/newsletter/newsletter_list.html
{% extends "clients/base.html" %}

{% block title %} Список рассылок {% endblock %}
{% block options %}
<a class="p-2 btn btn-outline-primary" href="{% url 'newsletter:create_newsletter' %}"
   role="button">Создать рассылку</a>
<a class="p-2 btn btn-outline-primary" href="{% url 'newsletter:create_message' %}"
   role="button">Создать сообщение для рассылки</a>
<a class="p-2 btn btn-outline-primary" href="{% url 'clients:clients' %}"
   role="button">Список клиентов</a>
<a class="p-2 btn btn-outline-primary" href="{% url 'blog:main_page' %}"
   role="button">Перейти в блог</a>
{% endblock %}
{% block content %}

<div class="container text-center">
    <div class="row">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">ID рассылки</th>
                <th scope="col">Получатели</th>
                <th scope="col">Сообщение</th>
                <th scope="col">Статус</th>
                <th scope="col">Дата следующей отправки</th>
                <th scope="col">Дата окончания</th>
                <th scope="col">Периодичность</th>
                <th scope="col">История</th>
            </tr>
            </thead>
            <tbody class="table-group-divider">
            {% for newsletter in newsletters %}
            <tr>
                <th scope="row"><a style="text-decoration:none; font-size: 20px;" href="{% url 'newsletter:detail_newsletter' newsletter.pk %}">{{ newsletter.pk }}</a></th>
                <td><a style="text-decoration:none; font-size: 20px;" href="{% url 'newsletter:recipients' newsletter.pk %}"
                       class="row-link">Просмотреть</a></td>
                <td><a style="text-decoration:none; font-size: 20px;" href="{% url 'newsletter:detail_message' newsletter.message.pk %}"
                       class="row-link">{{ newsletter.message.title }}</a></td>
                <td>{{ newsletter.status }}</td>
                {% if newsletter.start_date > newsletter.end_date %}
                <td>Скоро завершится</td>
                {% else %}
                <td>{{ newsletter.start_date }}</td>
                {% endif %}
                <td>{{ newsletter.end_date }}</td>
                <td>{{ newsletter.regularity }}</td>
                <td><a style="text-decoration:none; font-size: 20px;" href="{% url 'newsletter:attempts' newsletter.pk %}"
                       class="row-link">Просмотреть</a></td></td>
                {% if newsletter.status == 'создана' %}
                <td><button type="button" class="btn btn-primary">Запустить</button></td>
                {% elif newsletter.status == 'запущена' %}
                <td><button type="button" class="btn btn-danger">Остановить</button></td>
                {% else %}
                <td><button type="button" class="btn btn-secondary" disabled>Завершена</button></td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/newsletter_update_form.html
{% extends "clients/base.html" %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Редактирование рассылки</h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Изменить</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</form>
{% endblock %}

newsletter/templates/newsletter/recipients_list.html
{% extends "clients/base.html" %}

{% block title %} Просмотр получателей {% endblock %}
{% block client_addition %}
<a class="p-2 btn btn-outline-primary" href="{% url 'newsletter:newsletters' %}"
   role="button">Просмотр рассылок</a>
{% endblock %}
{% block content %}

<div class="container text-center">
    <div class="row">
        <table class="table">
            <thead>

            <tr>
                <th scope="col">#</th>
                <th scope="col">Клиент</th>
                <th scope="col">Адрес электронной почты</th>
            </tr>
            </thead>
            <tbody class="table-group-divider">
            {% for recipient in recipients %}
            <tr>
                <th scope="row">{{ recipient.pk }}</th>
                <td><a style="text-decoration:none; font-size: 20px;" href="{% url 'clients:detail_client' recipient.pk %}"
                       class="row-link">{{ recipient.get_full_name }}</a></td>
                <td>{{ recipient.email }}</td>
                </a>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

</div>


{% endblock %}