blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (
    ArticleCreateView,
    ArticleDeleteView,
    ArticleDetailView,
    ArticleUpdateView,
    main_page
)
from .apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("", cache_page(10)(main_page), name="main_page"),
    path("create/", ArticleCreateView.as_view(), name="create_article"),
    path("detail/<int:pk>/", ArticleDetailView.as_view(), name="detail_article"),
    path("update/<int:pk>/", ArticleUpdateView.as_view(), name="update_article"),
    path("delete/<int:pk>", ArticleDeleteView.as_view(), name="delete_article"),
]

clients/urls.py
from config.urls import path
from clients.apps import ClientsConfig
from .views import (
    ClientsListView,
    ClientsDetailView,
    ClientsCreateView,
    ClientsDeleteView,
    ClientsUpdateView,
)


app_name = ClientsConfig.name

urlpatterns = [
    path("", ClientsListView.as_view(), name="clients"),
    path("create_client/", ClientsCreateView.as_view(), name="create_client"),
    path("delete_client/<int:pk>", ClientsDeleteView.as_view(), name="delete_client"),
    path("edit_client/<int:pk>", ClientsUpdateView.as_view(), name="edit_client"),
    path("detail_client/<int:pk>", ClientsDetailView.as_view(), name="detail_client"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("", include("newsletter.urls", namespace="newsletter")),
    path("clients/", include("clients.urls", namespace="clients")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import NewsletterConfig
from .views import (
    NewsLetterListView,
    NewsLetterCreateView,
    NewsLetterDeleteView,
    NewsLetterDetailView,
    NewsLetterUpdateView,
    MessageCreateView,
    MessageUpdateView,
    MessageDetailView,
    MessageDeleteView,
    main_page,
    recipients_list,
    distribution_attempts,
)

app_name = NewsletterConfig.name

urlpatterns = [
    path("", main_page, name="main_page"),
    # CRUD urls for newsletter.
    path(
        "create_newsletter/", NewsLetterCreateView.as_view(), name="create_newsletter"
    ),
    path(
        "detail_newsletter/<int:pk>",
        NewsLetterDetailView.as_view(),
        name="detail_newsletter",
    ),
    path(
        "newsletters/", cache_page(60)(NewsLetterListView.as_view()), name="newsletters"
    ),
    path(
        "edit_newsletter/<int:pk>",
        NewsLetterUpdateView.as_view(),
        name="edit_newsletter",
    ),
    path(
        "delete_newsletter/<int:pk>",
        NewsLetterDeleteView.as_view(),
        name="delete_newsletter",
    ),
    # CRUD urls for messages.
    path("create_message/", MessageCreateView.as_view(), name="create_message"),
    path("detail_message/<int:pk>", MessageDetailView.as_view(), name="detail_message"),
    path("edit_message/<int:pk>", MessageUpdateView.as_view(), name="edit_message"),
    path("delete_message/<int:pk>", MessageDeleteView.as_view(), name="delete_message"),
    # url for getting recipients list.
    path("recipients/<int:pk>", recipients_list, name="recipients"),
    # url for
    path("newsletters/<int:pk>/attempts/", distribution_attempts, name="attempts"),
]

users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path

from .apps import UsersConfig
from .views import RegisterView, VerificationView, UsersListView, UsersDetailView

app_name = UsersConfig.name

urlpatterns = [
    # Login / Logout urls
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    # Change password urls
    path("password-change/", PasswordChangeView.as_view(), name="password_change"),
    path(
        "password-change/done/",
        PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    # Reset password urls
    path("password-reset", PasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset/done",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # User register url.
    path("register/", RegisterView.as_view(), name="register"),
    path("activate/<uid64>/<token>", VerificationView.as_view(), name="verification"),
    # Users urls
    path("users_list/", UsersListView.as_view(), name="users_list"),
    path("users_detail/<int:pk>/", UsersDetailView.as_view(), name="users_detail"),
]

blog/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Article(models.Model):

    title = models.CharField(max_length=100, verbose_name="заголовок")
    body = models.TextField(verbose_name="содержимое")
    image = models.ImageField(upload_to="blog/", verbose_name="изображение")
    views_count = models.PositiveIntegerField(default=0, verbose_name="количество  просмотров")
    publish = models.DateTimeField(auto_now_add=timezone.now(), verbose_name="дата публикации")

    class Meta:

        verbose_name = "статья"
        verbose_name_plural = "статьи"
        ordering = ["-publish"]
        indexes = [models.Index(fields=["-publish"]),]

    def __str__(self):
        return f"{self.title}"

blog/forms.py
from django import forms
from .models import Article


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

class ArticleCreateForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Article
        fields = ["title", "body", "image"]

class ArticleUpdateForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Article
        fields = ["title", "body", "image"]

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    UpdateView,
    DetailView,
    DeleteView,
)

from newsletter.models import NewsLetter
from .forms import ArticleCreateForm, ArticleUpdateForm
from .models import Article


# Create your views here.


#


class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreateForm
    success_url = reverse_lazy("blog:main_page")


class ArticleDetailView(DetailView):
    model = Article
    context_object_name = "article"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleUpdateForm
    success_url = reverse_lazy("blog:main_page")


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy("blog:main_page")


def main_page(request):
    newsletters_count = NewsLetter.objects.count()
    newsletters_count_active = NewsLetter.objects.filter(status="запущена").count()
    newsletter_unique_clients = (
        NewsLetter.objects.prefetch_related("recipients").distinct().count()
    )
    articles = Article.objects.order_by("?")[:3]
    context = {
        "newsletters_count": newsletters_count,
        "newsletters_count_active": newsletters_count_active,
        "newsletter_unique_clients": newsletter_unique_clients,
        "articles": articles,
    }
    return render(request, "blog/blog_main_page.html", context)

blog/templates/blog/article_confirm_delete.html
{% extends "clients/base.html" %}

{% block content %}
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">Удаление статьи</h5>
        <p class="card-text">Статья удалиться навсегда
            </p>
        <form method="post">
            {% csrf_token %}
            <p>Хотите удалить {{ article.title }} из  каталога?</p>
            <button type="submit" class="btn btn-danger">Подтвердить</button>
            <a href="{% url 'clients:clients' %}" class="btn btn-warning">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends "clients/base.html" %}
{% load my_tags %}


{% block content %}
<div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ article.title }}</h4>
                </div>
                <div class="card-body">
                    <p><img src="{{ article.image | media_filter }}" alt="Image not found" height="300" width="300"></p>
                    <p>{{ article.body | truncatechars:100 }}</p>
                    <p> Количество просмотров {{ article.views_count }} Дата публикации {{ article.publish }} </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/article_form.html
{% extends "clients/base.html" %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Написать  статью</h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Опубликовать</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</form>
{% endblock %}

blog/templates/blog/base.html
{% load static %}

<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script src="{% static 'js/color-modes.js' %}"></script>




    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
<main>
  <div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
        {% block options %} {% endblock %}


        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        <span class="fs-4">{% block title %}  {% endblock %}</span>
      </a>
      {% if request.user.is_authenticated %}
      Привет {{ request.user.email }}
      <a href="{% url 'users:logout' %}" class="p-2 btn btn-outline-primary" role="button">Выйти</a>
      {% else %}
      <a href="{% url 'users:login' %}" class="p-2 btn btn-outline-primary" role="button">Войти</a>
      {% endif %}
      {% if request.user.is_staff %}
      <a href="{% url 'users:users_list' %}" class="p-2 btn btn-outline-primary" role="button">Список пользователей</a>
      {% endif %}
    </header>
    {% block content %} {% endblock %}
    <footer class="pt-3 mt-4 text-body-secondary border-top">
      &copy; 2024
    </footer>
  </div>
</main>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

blog/templates/blog/blog_main_page.html
{% extends "clients/base.html" %}
{% load my_tags %}

{% block title %} Список рассылок {% endblock %}
{% block options %}
<a class="p-2 btn btn-outline-primary" href="{% url 'blog:create_article' %}"
   role="button">Написать статью в блог</a>
<a class="p-2 btn btn-outline-primary" href="{% url 'newsletter:newsletters' %}"
   role="button">Перейти в сервис рассылок</a>
{% endblock %}
{% block content %}
<div class="container text-center">
    <div class="row">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Количество рассылок</th>
                <th scope="col">Активных рассылок</th>
                <th scope="col">Уникальных клиентов</th>
            </tr>
            </thead>
            <tbody class="table-group-divider">
            <tr>
                <td>{{ newsletters_count }}</td>
                <td>{{ newsletters_count_active }}</td>
                <td>{{ newsletter_unique_clients }}</td>
            </tr>
            </tbody>
        </table>
        <div class="row">
            {% for article in articles %}
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ article.title }}</h4>
                </div>
                <div class="card-body">
                    <h5>{{ article.body }}</h5>
                    <p><img src="{{ article.image | media_filter }}" alt="Image not found" width="200" height="200"></p>
                    <p>Количество просмотров {{ article.views_count }} Дата публикации {{ article.publish }}</p>
                </div>
                <div class="card-footer">
                    <a class="btn btn-primary" href="{% url 'blog:detail_article' article.pk %}"
                       role="button">Просмотр</a>
                    <a class="btn btn-primary" href="{% url 'blog:update_article' article.pk %}"
                       role="button">Изменить</a>
                    <a class="btn btn-danger" href="{% url 'blog:delete_article' article.pk %}"
                       role="button">Удалить</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}