blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (
    ArticleCreateView,
    ArticleDeleteView,
    ArticleDetailView,
    ArticleUpdateView,
    main_page
)
from .apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("", cache_page(10)(main_page), name="main_page"),
    path("create/", ArticleCreateView.as_view(), name="create_article"),
    path("detail/<int:pk>/", ArticleDetailView.as_view(), name="detail_article"),
    path("update/<int:pk>/", ArticleUpdateView.as_view(), name="update_article"),
    path("delete/<int:pk>", ArticleDeleteView.as_view(), name="delete_article"),
]

clients/urls.py
from config.urls import path
from clients.apps import ClientsConfig
from .views import (
    ClientsListView,
    ClientsDetailView,
    ClientsCreateView,
    ClientsDeleteView,
    ClientsUpdateView,
)


app_name = ClientsConfig.name

urlpatterns = [
    path("", ClientsListView.as_view(), name="clients"),
    path("create_client/", ClientsCreateView.as_view(), name="create_client"),
    path("delete_client/<int:pk>", ClientsDeleteView.as_view(), name="delete_client"),
    path("edit_client/<int:pk>", ClientsUpdateView.as_view(), name="edit_client"),
    path("detail_client/<int:pk>", ClientsDetailView.as_view(), name="detail_client"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("", include("newsletter.urls", namespace="newsletter")),
    path("clients/", include("clients.urls", namespace="clients")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import NewsletterConfig
from .views import (
    NewsLetterListView,
    NewsLetterCreateView,
    NewsLetterDeleteView,
    NewsLetterDetailView,
    NewsLetterUpdateView,
    MessageCreateView,
    MessageUpdateView,
    MessageDetailView,
    MessageDeleteView,
    main_page,
    recipients_list,
    distribution_attempts,
)

app_name = NewsletterConfig.name

urlpatterns = [
    path("", main_page, name="main_page"),
    # CRUD urls for newsletter.
    path(
        "create_newsletter/", NewsLetterCreateView.as_view(), name="create_newsletter"
    ),
    path(
        "detail_newsletter/<int:pk>",
        NewsLetterDetailView.as_view(),
        name="detail_newsletter",
    ),
    path(
        "newsletters/", cache_page(60)(NewsLetterListView.as_view()), name="newsletters"
    ),
    path(
        "edit_newsletter/<int:pk>",
        NewsLetterUpdateView.as_view(),
        name="edit_newsletter",
    ),
    path(
        "delete_newsletter/<int:pk>",
        NewsLetterDeleteView.as_view(),
        name="delete_newsletter",
    ),
    # CRUD urls for messages.
    path("create_message/", MessageCreateView.as_view(), name="create_message"),
    path("detail_message/<int:pk>", MessageDetailView.as_view(), name="detail_message"),
    path("edit_message/<int:pk>", MessageUpdateView.as_view(), name="edit_message"),
    path("delete_message/<int:pk>", MessageDeleteView.as_view(), name="delete_message"),
    # url for getting recipients list.
    path("recipients/<int:pk>", recipients_list, name="recipients"),
    # url for
    path("newsletters/<int:pk>/attempts/", distribution_attempts, name="attempts"),
]

users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path

from .apps import UsersConfig
from .views import RegisterView, VerificationView, UsersListView, UsersDetailView

app_name = UsersConfig.name

urlpatterns = [
    # Login / Logout urls
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    # Change password urls
    path("password-change/", PasswordChangeView.as_view(), name="password_change"),
    path(
        "password-change/done/",
        PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    # Reset password urls
    path("password-reset", PasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset/done",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # User register url.
    path("register/", RegisterView.as_view(), name="register"),
    path("activate/<uid64>/<token>", VerificationView.as_view(), name="verification"),
    # Users urls
    path("users_list/", UsersListView.as_view(), name="users_list"),
    path("users_detail/<int:pk>/", UsersDetailView.as_view(), name="users_detail"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="электронная почта")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:

        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"
        indexes = [
            models.Index(fields=["email"]),
        ]
        permissions = [
            ("change_user_is_active", "Can change user status"),
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ["email", "password1", "password2"]

    def clean_email(self):
        data = self.cleaned_data["email"]
        if User.objects.only("email").filter(email=data).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует.")
        return data


class UserUpdateForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = User
        fields = [
            "is_active",
        ]

users/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, ListView, DetailView, UpdateView

from config.settings import EMAIL_HOST_USER
from .forms import UserRegisterForm, UserUpdateForm
from .models import User
from .token_generator import verification_token
from django.contrib.auth.models import Group

# Create your views here.


class RegisterView(SuccessMessageMixin, CreateView):

    model = User
    context_object_name = "user"
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_message = "Ссылка для подтверждения направлена на указанный email."
    success_url = "#"

    def form_valid(self, form):
        user_creation_form = form
        if user_creation_form.is_valid():
            new_user = user_creation_form.save(commit=False)
            new_user.set_password(form.cleaned_data["password1"])
            new_user.is_active = False
            new_user.save()
            domain = get_current_site(self.request).domain
            uid64 = urlsafe_base64_encode(force_bytes(new_user.pk))
            token = verification_token.make_token(new_user)
            link = reverse(
                "users:verification", kwargs={"uid64": uid64, "token": token}
            )
            activate_url = "http://" + domain + link
            email = user_creation_form.cleaned_data["email"]
            subject = "Уведомление о регистрации на платформе"
            message = f"Для завершения регистрации перейдите по ссылке {activate_url}"
            send_mail(
                subject,
                message,
                EMAIL_HOST_USER,
                [
                    email,
                ],
                fail_silently=True,
            )
        return super().form_valid(form)


class VerificationView(View):

    def get(self, request, uid64, token):
        uid64 = force_str(urlsafe_base64_decode(uid64))
        user = User.objects.get(pk=uid64)
        user.is_active = True
        group = Group.objects.get(name="Пользователи платформы")
        user.groups.add(group)
        user.save()
        return redirect("users:login")


class UsersListView(ListView):
    model = User
    context_object_name = "users"

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(is_staff=False)


class UsersDetailView(UpdateView):
    model = User
    context_object_name = "user"
    form_class = UserUpdateForm
    success_url = reverse_lazy("users:users_list")

    def form_valid(self, form):
        if self.request.method == "POST":
            form.save()
        else:
            form = form
        return super().form_valid(form)

users/templates/users/register.html
{% extends "clients/base.html" %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

  <form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Форма регистрации</h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/register_email.html
Ссылка для авторизации на платформе
{{ protocol }}://{{ domain }}{% url "users:login" %}

users/templates/users/user_form.html
{% extends 'clients/base.html' %}


{% block content %}
  <form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Редактирование профиля пользователя</h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Изменить</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</form>
{% endblock %}

users/templates/users/user_list.html
{% extends "clients/base.html" %}

{% block title %} Список рассылок {% endblock %}
{% block options %}
<a class="p-2 btn btn-outline-primary" href="{% url 'newsletter:create_newsletter' %}"
   role="button">Создать рассылку</a>
<a class="p-2 btn btn-outline-primary" href="{% url 'newsletter:create_message' %}"
   role="button">Создать сообщение для рассылки</a>
<a class="p-2 btn btn-outline-primary" href="{% url 'clients:clients' %}"
   role="button">Список клиентов</a>
{% endblock %}
{% block content %}

<div class="container text-center">
    <div class="row">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">ID пользователя</th>
                <th scope="col">Email</th>
                <th scope="col">Статус</th>
            </tr>
            </thead>
            <tbody class="table-group-divider">
            {% for user in users %}
            <tr>
                <th scope="row"><a style="text-decoration:none; font-size: 20px;" href="{% url 'users:users_detail' user.pk %}">{{ user.pk }}</a></th>
                <td>{{ user.email }}</td>
                {% if user.is_active %}
                <td><button type="button" class="btn btn-danger" >Заблокировать</button></td>
                {% else %}
                <td><button type="button" class="btn btn-success">Разблокировать</button></td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}